DRIVETRAIN_POWER_PIN = 1
MOTOR_IN1_PIN = 2
MOTOR_IN2_PIN = 3
MOTOR_EN_PIN = 4
SERVO_PIN = 5
STOPLIGHT_PIN = 6
REVERSELIGHT_PIN = 7
L_BLINKER_PIN = 8
R_BLINKER_PIN = 9

BLINKING_PERIOD = .5
N_PARKING_SENSORS = 6
